language: java
jdk: openjdk15
sudo: required
dist: trusty
addons: # get google-chrome-stable
  chrome: stable
cache:
  directories: $HOME/.m2
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
before_install:
  - cd JavaDirectory/
install:
  - wget -N http://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver